export type CuratedDhruService = {
      category: string;
      name: string;
      price: string;
};

export const curatedDhruServices: CuratedDhruService[] = [
      { category: 'APPLE CHECK SERVICES', name: 'APPLE SOLD BY & COUNTRY INFO', price: '1.80' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE GSX PREMIUM DETAILS', price: '2.00' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE REPLACEMENTS HISTORY', price: '0.70' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE GSX REPAIR ELIGIBILITY', price: '0.14' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE GSX CASES & REPAIRS', price: '1.20' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE ICLOUD ID HINT', price: '0.40' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE PART NUMBER - MPN', price: '0.155' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE CARRIER', price: 'FREE' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE CARRIER & FMI', price: '0.08' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE CARRIER & FMI & BLACKLIST', price: '0.10' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE MODEL COLOR & CAPACITY', price: '0.022' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE SIM-LOCK', price: 'FREE' },
      { category: 'APPLE CHECK SERVICES', name: 'IMEI SN CONVERT', price: '0.025' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE BASIC INFO', price: '0.05' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE SERIAL INFO', price: 'FREE' },
      { category: 'APPLE CHECK SERVICES', name: 'ICLOUD ON/OFF', price: 'FREE' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE ACTIVATION STATUS', price: '0.03' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE ACTIVATION STATUS - PRO', price: '0.04' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE DEMO DEVICES INFO', price: '0.20' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE MDM STATUS', price: '0.30' },
      { category: 'APPLE CHECK SERVICES', name: 'APPLE MDM & ICLOUD & GSX STATUS', price: '0.40' },
      { category: 'APPLE CHECK SERVICES', name: 'MACBOOK & IMAC ICLOUD ON/OFF STATUS', price: '0.20' },
      { category: 'APPLE CHECK SERVICES', name: 'IPHONE & MAC ICLOUD CLEAN/LOST STATUS', price: '0.22' },
      { category: 'STATUS CHECK SERVICES', name: 'AT&T USA STATUS & UNLOCK', price: '0.40' },
      { category: 'STATUS CHECK SERVICES', name: 'T-MOBILE USA STATUS - PRO', price: '0.05' },
      { category: 'STATUS CHECK SERVICES', name: 'CRICKET USA STATUS - PRO', price: '0.15' },
      { category: 'STATUS CHECK SERVICES', name: 'VERIZON USA STATUS - PRO', price: '0.07' },
      { category: 'STATUS CHECK SERVICES', name: 'VERIZON USA STATUS', price: '0.05' },
      { category: 'STATUS CHECK SERVICES', name: 'XFINITY USA STATUS - PRO', price: '0.08' },
      { category: 'STATUS CHECK SERVICES', name: 'CSPIRE USA STATUS - PRO', price: '0.08' },
      { category: 'STATUS CHECK SERVICES', name: 'TRACFONE USA STATUS - PRO', price: '0.06' },
      { category: 'STATUS CHECK SERVICES', name: 'WW BLACKLIST STATUS', price: '0.04' },
      { category: 'STATUS CHECK SERVICES', name: 'KOREA BLACKLIST STATUS', price: 'FREE' },
      { category: 'STATUS CHECK SERVICES', name: 'JAPAN BLACKLIST STATUS', price: 'FREE' },
      { category: 'STATUS CHECK SERVICES', name: 'AUSTRALIA BLACKLIST STATUS', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'ASUS INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'ACER INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'SPARX INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'HONOR INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'DOOGEE INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'HUAWEI INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'LENOVO INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'ALCATEL INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'KYOCERA INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'SAMSUNG INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'MOTOROLA INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'VIVO | IQOO INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'GOOGLE PIXEL INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'NOTHING PHONE INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'UNITY CELLECOR INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'SAMSUNG INFO - PRO', price: '0.105' },
      { category: 'GENERIC CHECK SERVICES', name: 'SAMSUNG KNOX GUARD INFO', price: '0.30' },
      { category: 'GENERIC CHECK SERVICES', name: 'ZTE | NUBIA | REDMAGIC INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'OPPO | ONEPLUS REALME INFO', price: '0.20' },
      { category: 'GENERIC CHECK SERVICES', name: 'ITEL INFINIX | TECNO | SONIM INFO', price: '0.035' },
      { category: 'GENERIC CHECK SERVICES', name: 'XIAOMI | REDMI | POCO MI LOCK ON/OFF INFO', price: '0.10' },
      { category: 'GENERIC CHECK SERVICES', name: 'XIAOMI | REDMI | POCO MI LOCK CLEAN/LOST INFO', price: '0.50' },
      { category: 'GENERIC CHECK SERVICES', name: 'BRAND & MODEL INFO', price: 'FREE' },
      { category: 'GENERIC CHECK SERVICES', name: 'SIM ICCID | IMSI INFO', price: 'FREE' },
      { category: 'PREMIUM CHECK SERVICES', name: 'MDM LOCK BYPASS - IPHONE/IPAD', price: '16.0' },
      { category: 'PREMIUM CHECK SERVICES', name: 'T-MOBILE USA UNBARRING LOST/STOLEN', price: '30.05' },
      { category: 'PREMIUM CHECK SERVICES', name: 'T-MOBILE USA UNBARRING PREMIUM', price: '50.05' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'AUSTRIA A1 MOBILKOM - OUT OF CONTRACT', price: '115' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'AUSTRIA A1 MOBILKOM PREMIUM', price: '165' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'CANADA FIDO/ROGERS - PREMIUM', price: '20' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'CANADA TELUS - CLEAN', price: '2.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'CLARO ALL COUNTRIES - PREMIUM (IPHONE 14)', price: '59.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'CLARO ALL COUNTRIES - PREMIUM (IPHONE 15)', price: '89.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'CLARO ALL COUNTRIES - PREMIUM (UP TO IPHONE 13)', price: '47.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'EMEA SERVICE - PREMIUM', price: '1.50' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'HUNGARY VODAFONE - PREMIUM (IPHONE 4S TO 11)', price: '66.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'JAPAN AU KDDI - CLEAN', price: '4.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'JAPAN NTT DOCOMO - CLEAN', price: '2.60' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'JAPAN SOFTBANK - CLEAN', price: '2.60' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'PHILIPPINES GLOBE - CLEAN', price: '5.50' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'ROMANIA ORANGE - PREMIUM', price: '14.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'ROMANIA VODAFONE - PREMIUM', price: '18.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'UK EE/T-MOBILE/ORANGE - PREMIUM', price: '2.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'UK O2 TESCO - CLEAN', price: '2.50' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'UK VODAFONE - CLEAN', price: '8.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'US RESELLER FLEX - CLEAN', price: '30.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'US RESELLER FLEX - PREMIUM', price: '168.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA AT&T - CLEAN/ACTIVE LINE', price: '8.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA AT&T - SOLD DATE: 60 DAYS', price: '28.05' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA C SPIRE - CLEAN', price: '2.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA CRICKET - CLEAN & 6 MONTHS OLD', price: '6.00' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA T-MOBILE - PREMIUM', price: '145.0' },
      { category: 'IPHONE UNLOCK SERVICES', name: 'USA VERIZON - CLEAN & ACTIVATED', price: '85.05' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'CANADA VIDEOTRON', price: '1.00' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'FRANCE BOUYGUES', price: '2.00' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'HTC INTERNATIONAL', price: '2.00' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'SAMSUNG EUROPE - LIMITED COUNTRIES', price: '14.05' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'SAMSUNG EUROPE - PREMIUM', price: '18.05' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'SAMSUNG UK & IRELAND - PREMIUM', price: '18.0' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'UK O2 - CLEAN', price: '7.50' },
      { category: 'GENERIC UNLOCK SERVICES', name: 'UK VODAFONE - CLEAN', price: '8.00' },
];

export const normalizeServiceName = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '');
